management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

server:
    port: 8080
    shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s